{% set name = "basedmypy" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/basedmypy-{{ version }}.tar.gz
  sha256: 489daaa7d6e2fdfe3db068ea499390f18d00fda66bccb273aaffc95e0768ac22

build:
  noarch: python
  entry_points:
    - mypy=mypy.__main__:console_entry
    - stubgen=mypy.stubgen:main
    - stubtest=mypy.stubtest:main
    - dmypy=mypy.dmypy.client:console_entry
    - mypyc=mypyc.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=40.6.2
    - wheel >=0.30.0
    - basedtyping >=0.0.3
    - typing_extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0
    - types-psutil
    - types-setuptools
    - mypy
    - mypyc
    - pip
  run:
    - python >=3.8
    - basedtyping >=0.0.3
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0
    - mypyc

test:
  imports:
    - mypy
    - mypyc
  commands:
    - pip check
    - mypy --help
    - stubgen --help
    - stubtest --help
    - dmypy --help
    - mypyc --help
  requires:
    - pip

about:
  home: https://github.com/KotlinIsland/basedmypy
  summary: Based static typing for Python
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - mypyc/external/googletest/LICENSE
    - mypy/typeshed/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
